### ISSUE TITLE
xoctException when trying to "Insert Opencast Video" in Page Edit

### ISSUE THREAD

**Issue by WKarlHGU** [opencast-ilias/OpencastPageComponent#32] opened 2024-09-19 05:50 UTC
When I edit an ilias page in a learning module and try to insert an opencast video, an exception is thrown:

    xoctException thrown with message "Not Found: OcSeriesApi -> getMetadata: [ (GET) /api/series//metadata] => Not Found"
    
    Stacktrace:
    #26 xoctException in /storage/ilias_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/API/DecorateProxy.php:94

**To reproduce:**

1. Open a learning module.
2. Click on a "+" Icon to add an element.
3. Select "Insert Opencast Video"

The a.m. exception ist thrown

**Environment:**
 - ILIAS version: v7.28 2024-02-14
 - PHP version: PHP 7.4.3-4ubuntu2.23
 - Opencast Plugin version: 7.0.5
 - Page Plugin Plugin version: 7.0.1
 - Browser: Firefox

**Comment by ferishili** [comment] 2024-09-19 09:17
Which Opencast version you are using?

**Comment by WKarlHGU** [comment] 2024-09-19 11:56
We are using version 15.7.0
Sorry for not giving this information.

**Comment by ferishili** [comment] 2024-09-19 12:48
From what I could understand, the `seriesId` is somehow missing.
The URL that is trying to get data from is: `/api/series//metadata`
But it has to be `/api/series/[missing series id]/metadata`

Maybe this could be a good clue where to look at!

**Comment by WKarlHGU** [comment] 2024-09-19 13:23
Well - at that point in time there *is* no seriesId. It is a neutral ilias page without connection to any series. I understand, that there should open a dropdown that allows me to select a series and then select one of its videos.

**Comment by ferishili** [comment] 2024-09-19 13:29
That sounds to me like a logical problem: (offering to add opencast video where it is not suitable)
It needs to be identified and prevented if this is the case!

**Comment by WKarlHGU** [comment] 2024-09-20 05:16
It **is** suitable because this option ("Insert Opencast Video") is offered in the context dialog. I expect the opencast page plugin to open a dialog to ask which series and then which video shoud be inserted. This is exactly what is triggered if I want to enter a new opencast object in a learning module. How else should it work? There is no other way to open a series on an ilias page, or is there a way?

**Comment by WKarlHGU** [comment] 2024-09-20 05:23
Furthermore, it is possible to have a video in opencast that does not belong to any series.

**Comment by WKarlHGU** [comment] 2024-10-04 11:49
From the main README.md in the root directory:

"The page editor action "Insert Opencast Video" offers a table to search videos from the configured Opencast installation (configuration of RepositoryObject plugin "Opencast" will be used). The table will show only videos accessible by the current user."

This is exactly what I am missing and what it should do.

**Comment by WKarlHGU** [comment] 2024-11-13 14:36
Anything new?

**Comment by chfsx** [comment] 2024-11-15 13:54
@WKarlHGU I'm unable to reproduce this issue using the lastest version of this plugin in combination with the Opencast-Plugin (which is needed). which version of both plugins are you using? in combination with which ILIAS Version?

@ferishili FYI: The page component plugins creates one series for the user which "holds" all the videos uploaded directly.

**Comment by dagraf** [comment] 2024-12-02 13:21
FYI and @WKarlHGU: As community for the Opencast plugins for ILIAS we stopped maintaining the branch "release_7" (which is needed for ILIAS 7) by end of September 2024.

**Comment by chfsx** [comment] 2024-12-17 16:01
If the problem no longer exists in release_8, I would suggest closing the issue.

**Comment by dagraf** [comment] 2024-12-17 16:08
Since this issue no longer exists in release_8, I close this issue.

**Closed as completed by dagraf** 2024-12-17 16:08 UTC
Labels: bug, ILIAS 7
